version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devbook
      MYSQL_USER: golang
      MYSQL_PASSWORD: golang
    ports:
      - "3306:3306"